export const policies = [
  {
    id: "001",
    customer: {
      firstName: "Elizabeth",
      lastName: "Bennet",
      dateOfBirth: new Date("December 16, 1775"),
    },
    provider: "Jane Health Inc.",
    insurance: "Health",
    status: "Active",
    policyNumber: "AB2819",
    startDate: new Date("July 16, 1776"),
    endDate: new Date("July 16, 1805"),
    createdAt: new Date("July 16, 1776"),
  },
  {
    id: "002",
    customer: {
      firstName: "Fitzwilliam",
      lastName: "Darcy",
      dateOfBirth: new Date("June 20, 1775"),
    },
    provider: "Austen Insurance Coop",
    insurance: "Liability",
    status: "Pending",
    policyNumber: "CD1289",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "003",
    customer: {
      firstName: "Elizabeth",
      lastName: "Bennet",
      dateOfBirth: new Date("December 16, 1775"),
    },
    provider: "Austen Insurance Coop",
    insurance: "Liability",
    status: "Cancelled",
    policyNumber: "CJ8289",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "004",
    customer: {
      firstName: "Fitzwilliam",
      lastName: "Darcy",
      dateOfBirth: new Date("June 20, 1775"),
    },
    provider: "Jane Health Inc.",
    insurance: "Liability",
    status: "Active",
    policyNumber: "CD1S89",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "005",
    customer: {
      firstName: "Fitzwilliam",
      lastName: "Darcy",
      dateOfBirth: new Date("June 20, 1775"),
    },
    provider: "Austen Insurance Coop",
    insurance: "Liability",
    status: "Active",
    policyNumber: "CD1S89",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "006",
    customer: {
      firstName: "Elizabeth",
      lastName: "Bennet",
      dateOfBirth: new Date("December 16, 1775"),
    },
    provider: "Jane Health Inc.",
    insurance: "Household",
    status: "Dropped",
    policyNumber: "CJ8289",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "007",
    customer: {
      firstName: "Elizabeth",
      lastName: "Bennet",
      dateOfBirth: new Date("December 16, 1775"),
    },
    provider: "Jane Health Inc.",
    insurance: "Liability",
    status: "Active",
    policyNumber: "CJ8289",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "008",
    customer: {
      firstName: "Elizabeth",
      lastName: "Bennet",
      dateOfBirth: new Date("December 16, 1775"),
    },
    provider: "Jane Health Inc.",
    insurance: "Liability",
    status: "out",
    policyNumber: "CJ8289",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "009",
    customer: {
      firstName: "Fitzwilliam",
      lastName: "Darcy",
      dateOfBirth: new Date("June 20, 1775"),
    },
    provider: "Austen Insurance Coop",
    insurance: "Health",
    status: "Active",
    policyNumber: "CD1S89",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
  {
    id: "010",
    customer: {
      firstName: "Fitzwilliam",
      lastName: "Darcy",
      dateOfBirth: new Date("June 20, 1775"),
    },
    provider: "Austen Insurance Coop",
    insurance: "Household",
    status: "Pending",
    policyNumber: "CD1S89",
    startDate: new Date("July 16, 1788"),
    endDate: new Date("July 16, 1816"),
    createdAt: new Date("July 16, 1786"),
  },
];
